# Generated by Django 3.2.4 on 2021-06-04 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScale',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interpolate', models.BooleanField(default=False)),
                ('r', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('g', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('b', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('a', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_source', models.CharField(help_text='Will create this sub folder under : ./data/', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Layer Title', max_length=255)),
                ('name', models.CharField(help_text='Layer identifier', max_length=100)),
                ('variable', models.CharField(help_text='Layer netcdf variable', max_length=100, unique=True)),
                ('time_generator', models.CharField(choices=[('mas', 'MAS')], default='mas', max_length=100)),
                ('offset_value', models.FloatField(default=0)),
                ('scale_value', models.FloatField(default=1)),
                ('clip_value', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('sub_path', models.CharField(max_length=100, unique=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='layermanager.geocollection')),
                ('color_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layermanager.colorscale')),
                ('time_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layermanager.timeinterval')),
            ],
        ),
        migrations.CreateModel(
            name='ColorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('threshold', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('r', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('g', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('b', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('a', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_values', to='layermanager.colorscale')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
