# Generated by Django 3.2.4 on 2021-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='file_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
