# Generated by Django 3.2.4 on 2021-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0002_layer_file_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='time_interval',
            field=models.CharField(blank=True, choices=[('day', 'Daily'), ('week', 'Weekly'), ('dekad', 'Dekadal'), ('month', 'Monthly'), ('season', 'Seasonal'), ('year', 'Yearly')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TimeInterval',
        ),
    ]
