# Generated by Django 3.2.4 on 2021-06-07 14:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0003_auto_20210607_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('method', models.CharField(choices=[('sum', 'Sum'), ('mean', 'Mean')], max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.layer')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_layers', to='layermanager.layer')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
