# Generated by Django 3.2.4 on 2021-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0004_derivedlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedlayer',
            name='file_name',
            field=models.CharField(default='PrecTotal', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
