# Generated by Django 3.2.4 on 2021-06-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0005_derivedlayer_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivedlayer',
            name='file_name',
        ),
    ]
