# Generated by Django 3.2.4 on 2021-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0009_layergrouplayer_file_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergrouplayer',
            name='file_match',
        ),
        migrations.AddField(
            model_name='layergroup',
            name='file_match',
            field=models.CharField(default='PrecExtreme', max_length=255),
            preserve_default=False,
        ),
    ]
