# Generated by Django 3.2.4 on 2021-06-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0010_auto_20210607_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergrouplayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_group', to='layermanager.layer'),
        ),
    ]
