# Generated by Django 3.2.4 on 2021-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0012_layer_shard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(help_text='Layer identifier', max_length=100, unique=True),
        ),
    ]
