# Generated by Django 3.2.4 on 2021-08-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0015_auto_20210804_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='layergroup',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category', null=True, on_delete=django.db.models.deletion.PROTECT, to='layermanager.datasetsubcategory'),
        ),
    ]
