# Generated by Django 3.2.4 on 2021-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0016_layergroup_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscale',
            name='legend_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('choropleth', 'Choropleth'), ('gradient', 'Gradient')], default='choropleth', help_text='Legend Type', max_length=100),
            preserve_default=False,
        ),
    ]
