# Generated by Django 3.2.4 on 2021-08-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0017_colorscale_legend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscale',
            name='the_rest_name',
            field=models.CharField(blank=True, help_text='Name for rest', max_length=100, null=True),
        ),
    ]
