# Generated by Django 3.2.4 on 2021-08-06 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0019_auto_20210806_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
