# Generated by Django 3.2.4 on 2021-08-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0020_auto_20210806_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layergroup',
            old_name='uuid',
            new_name='id',
        ),
    ]
