# Generated by Django 3.2.4 on 2021-08-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0021_rename_uuid_layergroup_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayerGroupLayer',
        ),
    ]
