# Generated by Django 3.2.4 on 2021-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0023_layergrouplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='variable',
            field=models.CharField(blank=True, help_text='Layer variable', max_length=100, null=True),
        ),
    ]
