# Generated by Django 3.2.4 on 2021-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0025_auto_20210812_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='use_file_time_pattern',
            field=models.BooleanField(default=False, help_text='Extract time details from file name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='file_time_pattern',
            field=models.CharField(blank=True, choices=[('(?P<year>\\d\\d\\d\\d)(?P<month>\\d\\d)(?P<day>\\d\\d).*_(?P<namespace>[\\w\\d_]+)', 'YYYYMMDD.*_namespace'), ('(?P<year>\\d\\d\\d\\d)(?P<month>\\d\\d).*_(?P<namespace>[\\w\\d_]+)', 'YYMM.*_namespace')], help_text='File Time Pattern', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='variable',
            field=models.CharField(default='var', help_text='Layer variable', max_length=100),
            preserve_default=False,
        ),
    ]
