# Generated by Django 3.2.4 on 2021-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0026_auto_20211028_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='pixel_stat',
            field=models.CharField(choices=[('mean', 'Mean'), ('sum', 'Sum'), ('minmaxmean', 'Min, Max, Mean')], default='mean', help_text='Pixel Statistic to Query with WPS', max_length=100),
        ),
        migrations.AlterField(
            model_name='layer',
            name='file_time_pattern',
            field=models.CharField(blank=True, choices=[('(?P<year>\\d\\d\\d\\d)(?P<month>\\d\\d)(?P<day>\\d\\d).*_(?P<namespace>[\\w\\d_]+)', 'YYYYMMDD.*_namespace'), ('(?P<year>\\d\\d\\d\\d)(?P<month>\\d\\d).*_(?P<namespace>[\\w\\d_]+)', 'YYMM.*_namespace'), ('_(?P<namespace>[\\w\\d_]+)', 'filename_namespace')], help_text='File Time Pattern', max_length=100, null=True),
        ),
    ]
