# Generated by Django 3.2.4 on 2021-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0027_auto_20211106_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='gsky_active',
            field=models.BooleanField(default=True, help_text='Activate in GSKY', verbose_name='Active in GSKY'),
        ),
    ]
