# Generated by Django 3.2.4 on 2021-11-15 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0028_layer_gsky_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='clip_value',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='offset_value',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='scale_value',
        ),
        migrations.AddField(
            model_name='colorscale',
            name='clip_value',
            field=models.FloatField(default=1, verbose_name='Maximum Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colorscale',
            name='offset_value',
            field=models.FloatField(default=0, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='colorscale',
            name='a',
            field=models.PositiveIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
    ]
