# Generated by Django 3.2.4 on 2021-11-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0030_alter_colorvalue_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorscale',
            old_name='clip_value',
            new_name='maximum_val',
        ),
        migrations.RenameField(
            model_name='colorscale',
            old_name='offset_value',
            new_name='minimum_val',
        ),
    ]
